[package]
name = "ass2txt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# encoding_rs = "0.8.33"
utf16_reader = "0.1.0"

